BEGIN;

DROP TABLE spaceman CASCADE;
DROP TABLE newspaper_spaceman CASCADE;
DROP TABLE newspaper CASCADE;
DROP TABLE topic CASCADE;
DROP TABLE planet CASCADE;
DROP TABLE spaceship CASCADE;
DROP TABLE flight CASCADE;
DROP TABLE flight_spaceman CASCADE;
DROP TYPE SEX;
DROP TYPE MODEL;
DROP TYPE GENRE;
DROP TYPE RANK;

COMMIT;